### ISSUE TITLE
Cannot connect to MATLink

### ISSUE THREAD

**Issue by jonluntzel** [rsmenon/MATLink#111]
Hi, having trouble connecting with 'Needs["MATLink`"] / OpenMATLAB[]', getting these errors:
![Merged_document](https://user-images.githubusercontent.com/34121312/121954461-9ef71e00-cd13-11eb-9c5c-d5a6c5729b62.png)
If I ignore the errors it runs indefinitely. Both the files _are_ located in the win64 folder that is in the path. What I tried:

Extracted the MATLink zip file in $UserBaseDirectory and ran regmatlabserver in MATLAB as an administrator, then ran those 2 lines in a notebook. Restarted Mathematica, double checked the added paths were present with 'Environment["PATH"]' and tried again.

I'm using Windows 10 64-bit, Mathematica 12.0, and MATLAB 2018b. I have C:\Program Files\MATLAB\R2018b\bin\win64 and C:\...\win64\bin added as path variables. I haven't yet tried reinstalling.

**Comment by szhorvat** [comment]
Can you show the output of the following, after running it in a newly started Mathematica session?

```
Needs["MATLink`"]
MATLink`Developer`GetInfo[]
```

**Comment by jonluntzel** [comment]
![Screenshot (144)](https://user-images.githubusercontent.com/34121312/122117436-b39ee900-cddb-11eb-8d04-5340b8fbe6c4.png)

**Comment by jonluntzel** [comment]
![Screenshot (145)](https://user-images.githubusercontent.com/34121312/122117539-d7fac580-cddb-11eb-94e9-f311100e3b8f.png)

**Comment by szhorvat** [comment]
I am not immediately sure what is wrong. There are some problems in the `PATH` setting though, and while these are unlikely to be causing the problem, please do correct them.

 - Remove the two `C` entries and the one empty entry from the `PATH`
 - Remove the two DLL files from the `PATH`. There should only be directories in there, not files.
 - Double check that there are no spaces on either side of the `;` separator in the `PATH`.

Since Window's PATH editor is pretty inconvenient, I find it easy to copy the whole string to a text editor (like Notepad), fix it, then paste it back.

----

In the past, others have reported similar errors when a conflicting DLL was present somewhere in the path. _Just in case_, please also move all the MATLAB-related entries to right after the last entry starting with `C:\Windows\...`.

**Comment by szhorvat** [comment]
Remember to fully restart Mathematica (not just the kernel) after editing the `PATH`, and verify that everything was fixed by looking at the output of `GetInfo[]`.

**Comment by jonluntzel** [comment]
It works. Much appreciated.
