### ISSUE TITLE
Mengine(2bwb8_shm) keeps hanging and cannot conncted to MATLAB

### ISSUE THREAD

**Issue by Beanhum** [rsmenon/MATLink#113]
**MEvaluate["mat = magic(4)"]** 
mat =

    16     2     3    13
     5    11    10     8
     9     7     6    12
     4    14    15     1

MEvaluate will output a magic square of size 4 but there is not  a variable named mat in the MATLAB 
workspace. 
![image](https://user-images.githubusercontent.com/92035910/136224180-e15000f8-b217-4792-b675-4ee6f5fd9fe6.png)

**MATLink`Developer`GetInfo[]**

MATLink 1.1 for Windows (Fri 15 Aug 2014)

12.2.0 for Microsoft Windows (64-bit) (February 1, 2021)

Force 32-bit engine: False

System PATH:
C:\Program Files\Wolfram Research\Mathematica\12.2\SystemFiles\Libraries\Windows-x86-64
C:\Program Files\Wolfram Research\Mathematica\12.2
C:\Program Files\Wolfram Research\Mathematica\12.2\SystemFiles\FrontEnd\Binaries\Windows-x86-64
C:\Program Files\Wolfram Research\Mathematica\12.2\SystemFiles\Kernel\Binaries\Windows-x86-64
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\Wolfram Research\WolframScript\
D:\Programme\Polyspace\R2021a\bin\win64
C:\Users\12631\AppData\Local\Microsoft\WindowsApps

D:\Programme\Microsoft VS Code\Microsoft VS Code\bin

COM server information:
CLSID: {E9358F45-85A1-4291-B997-3D4F7E0C3FBF}
Program ID: Matlab.Application (Version 9.10)
Command: D:\Programme\Polyspace\R2021a\bin\win64\MATLAB.exe /MLAutomation

**Comment by szhorvat** [comment]
> but there is not a variable named mat in the MATLAB
> workspace.

How do you conclude this? Can you show what you did to check whether there is such a variable?

For me, it works.

```
In[19]:= << MATLink`

In[21]:= OpenMATLAB[]

In[22]:= MEvaluate["mat = magic(4)"]

Out[22]= ">> 
mat =

    16     2     3    13
     5    11    10     8
     9     7     6    12
     4    14    15     1

"

In[23]:= MGet["mat"]

Out[23]= {{16., 2., 3., 13.}, {5., 11., 10., 8.}, {9., 7., 6., 
  12.}, {4., 14., 15., 1.}}
```

**Comment by Beanhum** [comment]
I conclude this because I find the workspace in my MATLAB is blank after I execute **MEvaluate["mat = magic(4)"]**
So do you mean, I don't have a real mat in MATLAB workspace? Thanks!

**Comment by szhorvat** [comment]
How do you determine that "the workspace in my MATLAB is blank"? You can list the variables in your workspace by evaluating `MEvaluate["who"]`. Does this not list `mat`?

Note that MATLink does not connect to an existing MATLAB session. It starts its own private MATLAB session which cannot interact with any other MATLAB instances that may have been running. The only exception is Windows, where you can follow these instructions: https://mathematica.stackexchange.com/a/69937/12

Since MATLink was written, MATLAB has gained new features that would make it possible to connect to arbitrary sessions, but taking advantage of them would require a full rewrite of MATLink (see #103). Realisitcally, I will not have the time for that in the foreseeable future.

**Comment by szhorvat** [comment]
Closing with the assumption that the problem was trying to connect to an already running MATLAB session. If you need additional help, please comment, and we can reopen the issue.
