### ISSUE TITLE
Passdown engineOpenQ status to avoid multiple checks for a single MFunction call

### ISSUE THREAD

**Issue by rsmenon** [rsmenon/MATLink#15]
MFunction checks if engineOpenQ 5 times per call. While it is negligible for a one time use, it is noticeable if the function is called repeatedly (in a loop).

**Comment by rsmenon** [comment]
this is now implemented.

**Comment by szhorvat** [comment]
I agree that this is a good thing.  I just want to mention (so we don't forget about the possibility) that MATLAB or the engine executable may crash as a result of engGet[], engSet[] or engEvaluate[], causing a cascade of errors which would be avoided by repeated engOpenQ checks.  If this crash happens, that should of course be considered a bug in MATLink, and fixed.

Situations where we can't really fix it are: 1. `engGet`ing a class.  This will crash on Unix due to a MATLAB Engine bug.  2. [Sending non-ASCII data to `engEvaluate` on Windows](https://github.com/rsmenon/MATLink/issues/9)
