### ISSUE TITLE
MEvaluate/MScript interprets \n in input MATLAB code as newlines

### ISSUE THREAD

**Issue by rsmenon** [rsmenon/MATLink#31]
`MEvaluate["disp('hello\nworld')"]` (or `MScript`) gives a "A quoted string is unterminated." error, because the `\n` in the input is interpreted as a new line when writing the script, which leads to a MATLAB syntax error.

**Comment by szhorvat** [comment]
I don't understand completely what is the problem here.  Can you elaborate? `"\n"`, in Mathematica syntax, _is_ an actual newline.  It's the same as typing

```
MEvaluate["disp('hello
world')"]
```

in Mathematica or typing

```
disp('hello
world')
```

in MATLAB.  I guess the way to include a newline is `MEvaluate["disp(sprintf('hello\\nworld'))"]` where `"\\"` is the Mathematica way to include `\` in the string.

What am I missing?

**Comment by rsmenon** [comment]
I know, I just didn't want the user to have to worry about escaping it. Closing this as "Stupid issue"
