### ISSUE TITLE
Clean up temporary files and directories

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#4]
It would be preferable not to leave a lot of junk in the temporary directory of the system.

I see two ways for now:
1. Either not create temporary files (probably unavoidable)
2. Clean them up on exit.  This is problematic again because creating a kernel-exit hook is possible, but messy and error prone

**Comment by rsmenon** [comment]
@szhorvat Clean-up of temporary files and directories is already implemented. When the exit is "clean" i.e., via `DisconnectMATLAB[]`, the temporary directory created for that session and all the files inside are removed. 

There is also the `MATLink`Developer`CleanupTemporaryDirectories[]` function which will remove all the temporary directories created in past hung/unclean exit sessions. At present, cleanup of old directories is not performed upon package load because I use the files in the previous session directories to debug/investigate when crashes occur. Eventually (in the release) it will be called in the `ConnectMATLAB[]` function, thus starting with a clean slate.

Closing this for now, since the functionality is there and has only been temporarily (and intentionally) disabled.

**Comment by szhorvat** [comment]
Doing it on startup is a good idea.  It should prevent accumulation of junk.  But are we sure that it is safe?  What if two instances of Mathematica are running at the same time (or just two kernels) and both are using MATLink?  Is there a chance that one of them will delete the files of the other while the other one is still  using them?

**Comment by rsmenon** [comment]
Good question... I'll have to think about this. One possible and safe way would be to only do "clean" removals (i.e., when disconnecting), but check on loading for temp directories and if there are more than 10 (say) give the user a warning and ask them to run `MATLink`Developer`CleanupTemporaryDirectories[]` before opening a new connection. The user can then decide a safe time to do this (and the warning remains till they do a cleanup).
