### ISSUE TITLE
Cannot open Matlab by OpenMATLAB[]

### ISSUE THREAD

**Issue by renphysics** [rsmenon/MATLink#53]
When I run OpenMATLAB[], it pops out that "The application was unable to start correctly (0xc000007b). Click OK to close the application."

Windows 7
Mathematica 9.0.1
Matlab 2012a
All are 64-bit.

**Comment by szhorvat** [comment]
Are you certain that your MATLAB is 64-bit?  Is it a student version by any chance?  This error typically occurs when you try to use a 32-bit MATLAB from a 64-bit Mathematica.

**Comment by szhorvat** [comment]
If it is a student version, then it is a 32-bit MATLAB.  In this case, do the following in a fresh Mathematica kernel:

```
Needs["MATLink`"]
SetOptions[MATLink, "Force32BitEngine" -> True]
```

If this is not the problem, please send an e-mail to matlink.m@gmail.com and let's continue in e-mail.

**Comment by renphysics** [comment]
I did that in a fresh Mathematica kernel, but I sill get the same message. My Matlab is under a site license, and it is 64-bit, which can be seen from Help->About MATLAB.

**Comment by szhorvat** [comment]
OK, then set it back: `SetOptions[MATLink, "Force32BitEngine" -> False]`.
This problem is very likely because mengine.exe is picking up the wrong DLLs.  Did you add MATLAB's `bin\win64` (but _not_ `bin\win32`) to the `PATH`?  A mistake there could cause this.

Can you send the output of this Mathematica command to us by private email?  `GetEnvironment["PATH"]`

**Comment by renphysics** [comment]
"SetOptions[MATLink, "Force32BitEngine" -> False]" solves the problem. Thanks!

(I run "SetOptions[MATLink, "Force32BitEngine" -> True]" before the first time I run OpenMATLAB[].)
