### ISSUE TITLE
great work -> how to see the matlab session under linux

### ISSUE THREAD

**Issue by ChristophKirst** [rsmenon/MATLink#59]
Hi,

MATLink works great for me and i am strting to use it more often.
I wonder if there is the possibility to open a matlab window and
see the evaluations done there or even interfere with them ?

In the current version the execution of matlab commands/session seems to be done in the background without opening the matlab interface, at e4last under
linux (openSuse) I am usnig.

Is there a way to see the workspace and matlab session etc opened by MATLink...

Thank you
Christoph

**Comment by szhorvat** [comment]
Hello Christoph,

This is not currently possible in the Linux and Mac versions due to the limitations of the API we are using to communicate with MATLAB.

If you use Windows, then `CommandWindow["Show"]` will bring up a MATLAB command window and it's also possible to interact with an already running instance of MATLAB with some setup.  But this is only avaliable on Windows.
