### ISSUE TITLE
Setting to Hide MATLAB Dock Icon & Loading Screen

### ISSUE THREAD

**Issue by tjrana** [rsmenon/MATLink#71]
I'd like to have a setting to be able to keep MATLAB hidden when running MATLink in Mathematica. Having a setting to disable the MATLAB dock icon and the MATLAB loading screen would be great!

**Comment by rsmenon** [comment]
I'm assuming you're on OS X, because of the other issue (#72) you raised. 
- Regarding the dock icon: this is how OS X apps work, and the behaviour should be overriden only by the developer of that app. MATLink should not (and will not) hijack other apps and change their behaviour. If you'd like to do this yourself, see [this article](http://www.cnet.com/news/prevent-an-applications-dock-icons-from-showing-in-os-x/) for the steps. However, note that making this change will affect all future invocations of MATLAB.
- As for the loading screen — MATLink invokes MATLAB with `matlab -nosplash`, which should not display the loading screen. Could you let us know your version info for MATLAB,  Mathematica and the operating system?

**Comment by szhorvat** [comment]
Actually I find having a dock icon useful.  Should something go wrong, there's an easy way to close the MATLAB process.  It's also easy to see if MATLAB is running.  It helps with avoiding zombie processes.
