### ISSUE TITLE
OpenMatlab[] keeps on Running....

### ISSUE THREAD

**Issue by carstenbauer** [rsmenon/MATLink#80]
Hi,

I followed the install instructions precisely (also the regmatlabserver and PATH variable stuff). Basically I have the same issue as in

https://github.com/rsmenon/MATLink/issues/79

but using MATLAB R2014b. I don't get any Error messages but after OpenMatlab[] it keeps on Running... forever without anything else.

I use Mathematica 10 64 bit and Matlab R2014b 64 bit.

Thanks in advance!

**Comment by szhorvat** [comment]
Please send an email to matlink.m at gmail with full information about your installation and operating system version.

First fully restart Mathematica, including the front end, then evaluate

```
Needs["MATLink`"]
MATLink`Developer`GetInfo[]
```

and include the output in your email.

After running OpenMATLAB[], check carefully for any dialog windows with error messages.  On Windows these may appear behind other windows so you may not notice them.

Do you have LabView installed?

Let us continue in email, as at this point the issue is not yet suitable for a bug report.

**Comment by szhorvat** [comment]
I won't be able to respond before Monday evening due to limited internet connectivity but do send the information please.

**Comment by carstenbauer** [comment]
Apparently, after a system reboot (I don't know why this would be necessary?) everything is working perfectly fine now! Anyhow, thanks for your quick answer!
