### ISSUE TITLE
Can MATLAB function handles point to Mathematica code?

### ISSUE THREAD

**Issue by Armavica** [rsmenon/MATLink#87]
Some functions in MATLAB (for example [`fminsearch`](https://fr.mathworks.com/help/matlab/ref/fminsearch.html)) take as argument [function handles](https://fr.mathworks.com/help/matlab/function-handles.html).

In my case, I would like to use MATLAB's optimization routines on a function programmed in Mathematica. Reading the MATLink documentation and examples, I understand that passing a pointer to a Mathematica function to MATLAB is not currently supported: is this planned (may I help?) or is it simply not possible?

**Comment by rsmenon** [comment]
You're right that this is not currently supported. This is because of limitations in the [MATLAB Engine](http://www.mathworks.com/help/matlab/matlab_external/introducing-matlab-engine.html), so you might even say that this is not possible with the current version of MATLink.

But calling _Mathematica_ functions from MATLAB is definitely possible using [MEX files](http://www.mathworks.com/help/matlab/ref/mex.html) and we have verified this in a prototype. We haven't pursued this further yet because:
1. There simply hasn't been much demand for this feature. 
   
   Szabolcs and I like it in principle and see many benefits from it (like `fminsearch` and other optimization/PDE routines where MATLAB is better), but in the 3 years that MATLink has been around and with thousands of users using it, we've only gotten about 2-3 requests for it. It appears that the primary user base of MATLink is a heavy _Mathematica_ user, who needs to only reach into MATLAB for using some shared code/data from colleagues. So they are mostly fine with the current one-directional flow. 
2. Neither of us currently have the time and bandwidth to devote to this.
   
   Moving to MEX is not a simple step — it requires changing a lot of the underlying architecture, so it would require a lot of development time (thus potential for new bugs), designing the UX when integrating the bi-directional flow in a way that feels natural in both systems (i.e. if you're calling _Mathematica_ from MATLAB, it should feel like you're writing MATLAB code and not some weird DSL). All this would necessitate another round of rigorous testing on a large combination matrix: P versions of MATLAB x Q versions of _Mathematica_ x R platforms x S versions of platform... that's a lot! Given the overall low demand for this feature and the stability of the current version of MATLink, we've put this on the back burner.

With that context, there aren't any currently scheduled/planned releases although we haven't ruled out any either. However, if you'd like to contribute, we would definitely welcome it!
